name: Test upload-release-action

on:
  workflow_dispatch:

jobs:
  # Workflows
  test_release_action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v2

    - name: Upload test release
      uses: Spikatrix/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: .github/workflows/main.yml
        tag: test
        overwrite: true
        prerelease: true
        target_commit: 9487bf5b1c87ba3d9d
        release_name: "Test build"
        body: "Test body"
