name: Test ssh

on:
  push:
    branches: master

  workflow_dispatch:

jobs:
  ssh-to-remote:
    runs-on: ubuntu-latest

    steps:
      - name: Hello There
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: touch hellothere
